### ISSUE TITLE
Custom Permissions for API Key Authentication

### ISSUE THREAD

**Issue by koladev32** [koladev32/drf-simple-apikey#67]
**Is your feature request related to a problem? Please describe.**

The current permission setup only allows one type of permission, `IsActiveEntity`, which checks if the user entity is active. This limitation can be frustrating in scenarios where fine-grained access control is needed. For instance, there is no way to enforce permissions such as read-only or create-only access, which are commonly required in multi-user environments and can improve security.

**Describe the solution you'd like**

We would like to add a set of additional permission classes to support more granular access control. This would provide flexibility in defining different access levels, such as:
- **ReadOnlyEntity**: Allows only GET requests.
- **CreateOnlyEntity**: Allows only POST requests.
- **UpdateOnlyEntity**: Allows only PUT/PATCH requests.

Each permission class would be added to enhance the security and control of API access, allowing us to define specific roles and enforce them at the API level.

**Describe alternatives you've considered**

We considered using a single permission class with additional logic to restrict access per request method, but this approach becomes cumbersome and lacks the clarity that separate permission classes can provide.

**Comment by TilteD24** [comment]
Working on this

**Comment by TilteD24** [comment]
Do you have any idea how to setup the development environment on windows ?
