### ISSUE TITLE
DOC errors

### ISSUE THREAD

**Issue by danielbolivar** [koladev32/drf-simple-apikey#76]
The documentation has some errors when addressing things related to the library like putting it in installed_apps:

The following wont work becase the name is written   "drf-simple-apikey" instead of   "drf_simple_apikey"
`# settings.py

INSTALLED_APPS = [
  # ...
  "rest_framework",
  "drf-simple-apikey",
]`

The same happens with drf_simple_apikey.analytics

**Comment by koladev32** [comment]
Closed with #77
